export const UNIT = [
  'SGOD',
  'CID',
  'HR',
  'RECORDS',
  'SUPPLY',
  'OSDS',
  'ASDS',
  'ACCOUNTING',
  'BUDGET',
  'CASHIER',
  'MEDICAL',
]

export const FILE_NAMES = [
  'ADMINISTRATION MANAGEMENT',
  'GENERAL SERVICES',
  'PROCUREMENT SERVICE SUPPLY PROPERTY RECORDS',
  'FINANCE MANAGEMENT',
  'ACCOUNTING RECORDS',
  'BUDGET RECORDS',
  'CASH RECORDS',
  'HEALTH NUTRITION SERVICES',
  'HUMAN RESOURCE MANAGEMENT SERVICES',
  'LEGAL SERVICES',
  'PHYSICAL FACILITIES SCHOOL ENGINEERING SERVICES',
  'BASIC EDUCATION INFORMATION SERVICES',
  'PLANNING SERVICES',
  'SCHOOL MANAGEMENT ALTERNATIVE LEARNING SYSTEM',
  'PROMOTIONAL DIVISION',
  'SCHOOL LEVEL RECORDS',
]

export const FILE_LOCATIONS = [
  'SHELF 1 - ADMINISTRATION & MANAGEMENT',
  'SHELF 2 - GENERAL SERVICES',
  'SHELF 3 - PROCUREMENT SERVICE AND SUPPLY/PROPERTY RECORDS',
  'SHELF 4 - FINANCE MANAGEMENT',
  'SHELF 5 - ACCOUNTING RECORDS',
  'SHELF 6 - BUDGET RECORDS',
  'SHELF 7 - CASH RECORDS',
  'SHELF 8 - HEALTH AND NUTRITION SERVICES, HUMAN RESOURCE MANAGEMENT SERVICES, LEGAL SERVICES',
  'SHELF 9 - PHYSICAL FACILITIES AND SCHOOL ENGINEERING SERVICES',
  'SHELF 10 - BASIC EDUCATION INFORMATION SERVICES',
  'SHELF 11 - PLANNING SERVICES',
  'SHELF 12 - SCHOOL MANAGEMENT ALTERNATIVE LEARNING SYSTEM',
  'SHELF 13 - PROMOTIONAL DIVISION',
  'SHELF 14 - SCHOOL LEVEL RECORDS',
]

export const FILE_STATUS = [
  'FOR DISPOSAL',
  'FOR ARCHIVING',
  'PENDING',
]
